---
# The services section defines the services that will be run in the Docker Compose environment.
services:
  # Base Go service image build configuration
  service_base:
    build:
      context: .
      dockerfile: ./services/service_base_docker/Dockerfile
    image: service-base:latest
    entrypoint: ["true"]

  # Postgres SQL DB service configuration
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_HOST_DB_PATH}:/var/lib/postgresql/data

  # News Checker service configuration
  news-checker:
    container_name: news_checker
    build:
      context: .
      dockerfile: ./services/news_checker/Dockerfile
    restart: unless-stopped
    depends_on:
      - service_base
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      MIGRATIONS_DIR: /app/internal/storage/migrations

volumes:
  postgres_data:
