---
# Base migration service
x-go-service-base: &go-service-base
  env_file:
    - .env
  depends_on:
    - postgres
  working_dir: /app
  environment:
    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable

x-gouse-base: &gouse-base
  <<: *go-service-base
  build:
    context: ${GOUSE_MIGRATE_PATH}
  volumes:
    - ${GOUSE_MIGRATE_PATH}:/app

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_HOST_DB_PATH}:/var/lib/postgresql/data

  gouse-migrate:
    container_name: gouse_migrate
    <<: *gouse-base
    # You can override or add fields here, e.g.:
    command: ["go", "run", "main.go", "up", "-migrations=./migrations"]

  gouse-migrate-down:
    container_name: gouse_migrate_down
    <<: *gouse-base
    command: ["go", "run", "main.go", "down", "-migrations=./migrations"]

  news-checker:
    container_name: news_checker
    <<: *go-service-base
    build:
      context: ./services/news_checker
    depends_on:
      - postgres
      - gouse-migrate
    volumes:
      - ./services/news_checker:/app
    command: ["go", "run", "main.go"]

volumes:
  postgres_data:
