---
# Base go service configuration
x-go-service-base: &go-service-base
  env_file:
    - .env
  working_dir: /app
  environment:
    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable

# Base migration service configuration
x-gouse-base: &gouse-base
  <<: *go-service-base
  build:
    # The path to the Dockerfile relative the context
    dockerfile: ../Dockerfile
    context: ${GOUSE_MIGRATE_PATH}
  depends_on:
    - postgres
  volumes:
    - ${GOUSE_MIGRATE_PATH}:/app

# The services section defines the services that will be run in the Docker Compose environment.
services:
  # Postgres SQL DB service configuration
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_HOST_DB_PATH}:/var/lib/postgresql/data

  # Gouse migration services configurations
  gouse-migrate:
    container_name: gouse_migrate
    <<: *gouse-base
    command: ["go", "run", "main.go", "up", "-migrations=./migrations"]

  gouse-migrate-down:
    container_name: gouse_migrate_down
    <<: *gouse-base
    command: ["go", "run", "main.go", "down", "-migrations=./migrations"]

  # News Checker service configuration
  news-checker:
    container_name: news_checker
    <<: *go-service-base
    restart: unless-stopped
    build:
      # The path to the Dockerfile relative the context
      dockerfile: ../Dockerfile
      context: ${NEWS_CHECKER_PATH}
    depends_on:
      - postgres
      - gouse-migrate
    volumes:
      - ${NEWS_CHECKER_PATH}:/app
    command: ["go", "run", "main.go"]

volumes:
  postgres_data:
